version: '2'
services:
  streamdc:
    image: "streamsets/datacollector"
    container_name: "streamdc"
    hostname: streamdc
    restart: always
    ports:
      - 18630:18630
    environment:
      STREAMSETS_LIBRARIES_EXTRA_DIR: /opt/sdc-extras
    volumes:
      - ./dctutorial:/home/sdc/tutorial/origin2
      - ./dcdata:/data
      - ./sdcextra:/opt/sdc-extras
  main_node:
    image: "datastax/dse-server"
    container_name: "dse"
    hostname: dse
    ports:
    - "4040:4040"
    - "7080:7080"
    - "7199:7199"
    - "8182:8182"
    - "8983:8983"
    - "9042:9042"
    environment:
      - DS_LICENSE=accept
      - CLUSTER_NAME=main
    # Allow DSE to lock memory with mlock
    cap_add:
    - IPC_LOCK
    ulimits:
      memlock: -1
    volumes:
      - ./data:/var/lib/cassandra/data
      - ./conf:/config
      - ./logs:/var/lib/cassandra/commit_logs
      - ./cache:/var/lib/cassandra/saved_caches
      - ./confy:/etc/dse/conf
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zoo1"
    hostname: "zoo1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    container_name: "kafka1"
    hostname: "kafka1"
    ports:
      - "9092"
    environment:
      HOSTNAME_COMMAND: "echo $$(hostname)"
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
